### ISSUE TITLE
chrome extn: is tabs permissions required

### ISSUE THREAD

**Issue by muly** [muly/product-track#48]
is the `activeTab` permission not good enough? do we also need the `tabs` permission?

**Comment by muly** [comment]
per this video, it looks like we can pull the active tab "url" within the chrome extension just by using the activeTab permission. what else do we need the tabs permission for?
https://www.youtube.com/watch?v=giCc-8KP3Ak

**Comment by Rohithknaidu** [comment]
> per this video, it looks like we can pull the active tab "url" within the chrome extension just by using the activeTab permission. what else do we need the tabs permission for? https://www.youtube.com/watch?v=giCc-8


> is the `activeTab` permission not good enough? do we also need the `tabs` permission?

i didnot get the  active tab url some times.
